name: contact_picker
description: A Flutter plugin for picking a contact from the address book.
version: 0.0.4
authors: 
  Michael Goderbauer <michael@goderbauer.net>
  Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/appleeducate/contact_picker

flutter:
  plugin:
    androidPackage: com.appleeducate.flutter.contactpicker
    pluginClass: ContactPickerPlugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
